version: '3'

services:
    sswt_frontend:
        image: soliddevnl/sswt-frontend:main
        ports:
            - 3000:3000
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
            interval: 5s
            timeout: 10s
            retries: 10

    sswt_api:
        image: soliddevnl/sswt-api:main
        ports:
            - 8000:8000

    webserver:
        depends_on:
            sswt_api:
                condition: service_started
            sswt_frontend:
                condition: service_healthy
        image: caddy:2.6-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
