version: '3'

services:
    sswt_frontend:
        image: soliddevnl/sswt-frontend:main
        ports:
            - 3000:3000

    sswt_api:
        image: soliddevnl/sswt-api:main
        ports:
            - 8000:8000