version: '3'

services:
    sswt_frontend:
        image: soliddevnl/sswt-frontend:main
        ports:
            - 3000:3000

    webserver:
        image: caddy:2.6-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
