name: Acceptance Stage

on:
    workflow_run:
        workflows: ['Commit Stage']
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   uses: isbang/compose-action@v1.4.1
                with:
                    compose-file: "./apps/sswt-control/docker-compose.acceptance.yml"

            -   name: Use Node.js 18.x
                uses: actions/setup-node@v3
                with:
                    node-version: 18.x

            -   name: Install Dependencies
                run: yarn install --frozen-lockfile

            -   name: Run acceptance tests
                run: yarn test:acceptance

            -   name: SCP the sswt-control folder to the server
                uses: appleboy/scp-action@v0.1.3
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USER }}
                    key: ${{ secrets.SSH_KEY }}
                    source: "apps/sswt-control/"
                    target: "./sswt"
                    strip_components: 1

            -   name: Let sswt-control deploy the new version
                uses: appleboy/ssh-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USER }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        cd ./sswt/sswt-control
                        echo "API_URL=${{ vars.API_URL }}" > .env
                        docker compose -f docker-compose.uat.yml pull
                        docker compose -f docker-compose.uat.yml down
                        docker compose -f docker-compose.uat.yml up -d