name: Commit stage
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build_frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/sswt-frontend
        steps:
            -   uses: actions/checkout@v3

            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18.13.0'

            -   name: Build app
                run: yarn install

            -   name: Build app
                run: yarn build

    build_api:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/sswt-api
        steps:
            -   uses: actions/checkout@v3

            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18.13.0'

            -   name: Build app
                run: yarn install

            -   uses: isbang/compose-action@v1.4.1
                with:
                    compose-file: "./apps/sswt-api/docker-compose.test.yaml"

            -   name: Run unit tests
                run: yarn test-unit

            -   name: Run integration tests
                run: yarn test-integration

    create_rc_api:
        needs: build_api
        runs-on: ubuntu-latest
        if: success()
        steps:

            -   name: Checkout
                uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: soliddevnl/sswt-api

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                file: ./apps/sswt-api/Dockerfile
                context: ./apps/sswt-api
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    create_rc_frontend:
        needs: build_frontend
        runs-on: ubuntu-latest
        if: success()
        steps:

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: soliddevnl/sswt-frontend

            -   name: Build and push Docker image
                uses: docker/build-push-action@v4
                with:
                    file: ./apps/sswt-frontend/Dockerfile
                    context: ./apps/sswt-frontend
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}